### ISSUE TITLE
HDMI issue

### ISSUE THREAD

**Issue by adibaulia** [DagerDW/Lenovo-ideapad-3-14iil05-Hackintosh#1]
Apakah EFI ini ada issue dengan port HDMI yang gabisa connect dan tidak muncul gambar nya di second monitor? Saya pakai laptop serupa namun pakai varian graphic G1. Thankyou

**Comment by DagerDW** [comment]
> Apakah EFI ini ada issue dengan port HDMI yang gabisa connect dan tidak muncul gambar nya di second monitor? Saya pakai laptop serupa namun pakai varian graphic G1. Thankyou

Iya mas, baik G1 atau G4 ada bug untuk HDMI port, seperti yang di bahas di [Insanlymac Forum](https://www.insanelymac.com/forum/topic/344939-general-discussion-intel-ice-lake-graphics-on-macos-catalina/)
